---
- hosts: all
  become: yes
  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
  tasks:
    - import_tasks: tasks/essential.yml

- hosts: dev
  pre_tasks:    
    - name: Create local /tmp dir
      become: false
      file:
        path: "/home/{{ username }}/tmp"
        state: directory
        mode: 0755
    - name: pre-Update packages (Debian-based)
      become: true
      apt:
        update_cache: "yes"
        upgrade: "yes"
      when: ansible_facts['os_family'] == "Debian"
  roles:
    - nodejs
    - podman
    - python
  post_tasks:
    - name: Delete local /tmp
      become: false
      file:
        path: "/home/{{ username }}/tmp"
        state: absent

- hosts: vpn
  roles:
    - fail2ban
  