- name: Update packages (Debian-based)
  become: true
  apt:
    update_cache: "yes"
    upgrade: "yes"
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages
  become: true
  package:
    name: "{{ packages }}"
    state: latest
