---
- name: Update packages (Debian-based)
  become: true
  apt:
    update_cache: "yes"
    upgrade: "yes"
  when: ansible_facts['os_family'] == "Debian"

- name: Install deps (Debian)
  become: true
  package:
    name: " {{ python_deps }}"
    state: latest

- name: Ensure Pyenv is installed
  stat:
    path: ~/.pyenv
  register: pyenv_details

- name: Download pyenv's install script
  get_url:
    url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
    dest: /tmp
    mode: 0755
  when: pyenv_details.stat.exists == false

- name: Run pyenv's install script
  shell: "/tmp/pyenv-installer"
  when: pyenv_details.stat.exists == false

- name: Delete pyenv's install script
  file:
    path: "/tmp/pyenv-installer"
    state: absent

- name: Update .bashrc
  lineinfile:
    backup: yes
    dest: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - export PYENV_ROOT="$HOME/.pyenv"
    - command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    - echo "pyenv On"
    - export PATH="~/.local/bin:$PATH"
